export const HOME_SWITCH_STATE = 'HOME_SWITCH_STATE';
export const HOME_UPDATE_MESSAGES = 'HOME_UPDATE_MESSAGES';
export const HOME_UPDATE_LOGS = 'HOME_UPDATE_LOGS';
export const HOME_CLEAR_LOGS = 'HOME_CLEAR_LOGS';
